name: Build iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files
        run: ls -R

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List schemes
        run: xcodebuild -list

      - name: Clean build
        run: xcodebuild clean -scheme AutoTouchApp

      - name: Build app
        run: |
          xcodebuild \
          -scheme AutoTouchApp \
          -configuration Release \
          -sdk iphonesimulator \
          build

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/*
