name: iOS Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Show files
        run: ls -R

      - name: Build simple iOS app (no project)
        run: |
          xcrun clang++ -fobjc-arc \
          -framework UIKit \
          -framework Foundation \
          -o build_app \
          main.mm AppDelegate.mm ViewController.mm

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build_app
